# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 4, 1, 1)
        self.input_coeff = QtWidgets.QLineEdit(self.centralwidget)
        self.input_coeff.setObjectName("input_coeff")
        self.gridLayout.addWidget(self.input_coeff, 1, 5, 1, 1)
        self.input_count = QtWidgets.QLineEdit(self.centralwidget)
        self.input_count.setObjectName("input_count")
        self.gridLayout.addWidget(self.input_count, 2, 5, 1, 1)
        self.input_side = QtWidgets.QLineEdit(self.centralwidget)
        self.input_side.setObjectName("input_side")
        self.gridLayout.addWidget(self.input_side, 0, 5, 1, 1)
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 4, 1, 1, 5)
        self.btn_draw = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_draw.setFont(font)
        self.btn_draw.setObjectName("btn_draw")
        self.gridLayout.addWidget(self.btn_draw, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "coeff"))
        self.label.setText(_translate("MainWindow", "side"))
        self.label_2.setText(_translate("MainWindow", "count"))
        self.image_label.setText(_translate("MainWindow", "TextLabel"))
        self.btn_draw.setText(_translate("MainWindow", "Нарисовать"))
