# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Antiplagiat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_check.setFont(font)
        self.btn_check.setObjectName("btn_check")
        self.gridLayout.addWidget(self.btn_check, 8, 0, 1, 2)
        self.text_edit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit_2.setObjectName("text_edit_2")
        self.gridLayout.addWidget(self.text_edit_2, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_threshold = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_threshold.setObjectName("input_threshold")
        self.horizontalLayout.addWidget(self.input_threshold)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.text_edit_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit_1.setObjectName("text_edit_1")
        self.gridLayout.addWidget(self.text_edit_1, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_check.setText(_translate("MainWindow", "Проверить"))
        self.label_2.setText(_translate("MainWindow", "Текст 1"))
        self.label.setText(_translate("MainWindow", "Порог срабатывания (%)"))
        self.label_3.setText(_translate("MainWindow", "Текст 2"))
