# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Psevdonim.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_count = QtWidgets.QSpinBox(self.centralwidget)
        self.input_count.setObjectName("input_count")
        self.gridLayout.addWidget(self.input_count, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_set_count = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_set_count.setFont(font)
        self.btn_set_count.setObjectName("btn_set_count")
        self.gridLayout.addWidget(self.btn_set_count, 0, 2, 1, 1)
        self.remnant_of_stones = QtWidgets.QLCDNumber(self.centralwidget)
        self.remnant_of_stones.setObjectName("remnant_of_stones")
        self.gridLayout.addWidget(self.remnant_of_stones, 1, 0, 1, 3)
        self.count_take = QtWidgets.QSpinBox(self.centralwidget)
        self.count_take.setObjectName("count_take")
        self.gridLayout.addWidget(self.count_take, 2, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.btn_take_stones = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_take_stones.setFont(font)
        self.btn_take_stones.setObjectName("btn_take_stones")
        self.gridLayout_2.addWidget(self.btn_take_stones, 1, 0, 1, 1)
        self.moves_sheet = QtWidgets.QListWidget(self.centralwidget)
        self.moves_sheet.setObjectName("moves_sheet")
        self.gridLayout_2.addWidget(self.moves_sheet, 2, 0, 1, 1)
        self.winner = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.winner.setFont(font)
        self.winner.setAlignment(QtCore.Qt.AlignCenter)
        self.winner.setObjectName("winner")
        self.gridLayout_2.addWidget(self.winner, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Сколько камней взять?"))
        self.label.setText(_translate("MainWindow", "Задать количество камней"))
        self.btn_set_count.setText(_translate("MainWindow", "Задать"))
        self.btn_take_stones.setText(_translate("MainWindow", "Взять"))
        self.winner.setText(_translate("MainWindow", "TextLabel"))
