name = input()
surname = input()
animal = input()
zodiacSign = input()
print("Индивидуальный гороскоп для пользователя", name, surname)
print("Кем вы были в прошлой жизни:", animal)
print("Ваш знак зодиака -", zodiacSign, ", поэтому вы - тонко чувствующая натура.")